CREATE TABLE PRODUCTS(
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(100)
)

CREATE TABLE CATEGORIES(
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR (100)
)

CREATE TABLE MARKET(
 ID INT PRIMARY KEY NOT NULL,
 PRODUCT_ID INT  FOREIGN KEY REFERENCES PRODUCTS,
 CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORIES
)

INSERT INTO PRODUCTS VALUES
  (1,'APPLE'),
  (2,'MEAT'),
  (3,'BEANS'),
  (4,'CAR WHEELS');
  

INSERT INTO CATEGORIES VALUES
  (1,'VEG'),
  (2,'MEAT PRODUCTS'),
  (3,'COLD PRODUCTS');
  
INSERT INTO MARKET VALUES
  (1,1,1),
  (2,3,1),
  (3,2,2),
  (4,2,3),
  (5,3,3);
  
  SELECT PRODUCTS.NAME, CATEGORIES.NAME
  FROM PRODUCTS
  LEFT JOIN MARKET ON PRODUCTS.ID = MARKET.PRODUCT_ID
  LEFT JOIN CATEGORIES ON CATEGORIES.ID = MARKET.CATEGORY_ID